baseurl:
#baseurl: /www
#port: 341
url: http://ef.thxopen.com
encoding: utf-8
exclude: ["README.md","*.iml","template"]
#destination: ./_site
#destination: C:\code\xampp\htdocs
email: keith@thxopen.com
github: https://github.com/ssy341/ef.thxopen.com

# page config
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "/note/page:num/"

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
#markdown_ext: "markdown,mkdown,mkdn,mkd,md"
sitename: Keith's EF Life