baseurl:
#baseurl: /www
#port: 341
url: http://ef.thxopen.com
encoding: utf-8
exclude: ["README.md"]
#destination: ./_site
#destination: C:\code\xampp\htdocs
email: thxopen@datatables.club
github: https://github.com/ssy341/ef.thxopen.com

# page config
gems: [jekyll-paginate]
paginate: 10
paginate_path: "/blog/page:num/"

excerpt_separator: <!--more-->

# Build settings
markdown: kramdown
#markdown_ext: "markdown,mkdown,mkdn,mkd,md"
sitename: Keith's EF Life
description: > # this means to ignore newlines until "baseurl:"
